# Matrix multiplication — practice (worked & executed)

In [1]:
import numpy as np
A=np.array([[1,2],[0,1.]]); B=np.array([[2,0],[1,3.]])
print("A@B=\n",A@B,"\nB@A=\n",B@A,"\ncommute:",np.allclose(A@B,B@A))

A@B=
 [[4. 6.]
 [1. 3.]] 
B@A=
 [[2. 4.]
 [1. 5.]] 
commute: False


### E1 — swap columns

In [2]:
print(np.array([[1,2],[3,4]])@np.array([[0,1],[1,0]]))   # [[2,1],[4,3]]

[[2 1]
 [4 3]]


### E2 — order matters

In [3]:
A=np.array([[2,0],[0,1]]); B=np.array([[1,1],[0,1]]); print(A@B,"\n",B@A)

[[2 2]
 [0 1]] 
 [[2 1]
 [0 1]]


### E3 — valid shapes

In [4]:
def shp(a,b):
    try: return (np.zeros(a)@np.zeros(b)).shape
    except Exception: return "invalid"
for a,b in [((4,3),(3,2)),((3,2),(3,2)),((1,5),(5,1)),((5,1),(1,5))]:
    print(a,"@",b,"->",shp(a,b))

(4, 3) @ (3, 2) -> (4, 2)
(3, 2) @ (3, 2) -> invalid
(1, 5) @ (5, 1) -> (1, 1)
(5, 1) @ (1, 5) -> (5, 5)


### E4 — associativity

In [5]:
rng=np.random.default_rng(0); A,B,C=(rng.random((2,2)) for _ in range(3))
print(np.allclose(A@(B@C),(A@B)@C))

True


### E5 — matrix power

In [6]:
R=np.array([[0,-1],[1,0]]); print(np.linalg.matrix_power(R,4))   # I

[[1 0]
 [0 1]]
